# https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts
issuer: https://vault.us1.ddbuild.io/v1/identity/oidc
subject_pattern: cbeb6072-9e0d-0299-72a9-9b2b7512acaf


permissions:
  contents: write
