# https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts
issuer: https://gitlab.ddbuild.io
subject_pattern: project_path:DataDog/datadog-cdk-constructs:.*

claim_pattern:
  name: gitlab-runner-datadog-cdk-constructs


permissions:
  contents: write
