# https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/5138645099/User+guide+dd-octo-sts
issuer: https://gitlab.ddbuild.io
subject_pattern: project_path:DataDog/datadog-cdk-constructs:.*

claim_pattern:
  project_path: DataDog/datadog-cdk-constructs


permissions:
  actions: write
  actions_variables: read
  administration: read
  checks: write
  contents: write
  deployments: write
  discussions: write
  environments: write
  issues: write
  members: read
  merge_queues: read
  metadata: read
  organization_actions_variables: read
  organization_administration: read
  organization_events: read
  organization_projects: write
  packages: write
  pages: read
  pull_requests: write
  repository_advisories: read
  repository_projects: write
  secret_scanning_alerts: read
  security_events: write
  statuses: write
  vulnerability_alerts: read
  workflows: write